app:
    data:
        repos:
            primary-repository-path: .work/calculations

    service:
        mapping:
            math-solvers-beans-xml-path: .work/resources/application.service.mapping.math-solvers-beans.xml
            deser-types-map-file-path: .work/resources/application.service.mapping.deser-types-map.yml
